<?php
$title = $this->translate('Add Tax');
$this->headTitle($title);
$this->pageBreadcrumbs()->setItems([
            $this->translate('Tax')=>$this->url('tax'),
            $this->translate('Add')=>$this->url('tax', ['action'=>'add']),
            ]);
$this->mainMenu()->setActiveItemId('tax');
$form->get('amount_upto')->setAttributes(['class'=>'form-control', 'placeholder'=>'Amount Upto']);
$form->get('tax_percentage')->setAttributes(['id'=>'is_primary','class'=>'form-control', 'placeholder'=>'Tax Percentage']);
$form->get('submit')->setAttributes(['class'=>'btn btn-primary'])->setValue($this->translate('Add Tax'));
$form->prepare();
$this->PageActions()->setItems([
            ['label'=>'Back to Tax','url'=>$this->url('tax'),'icon'=>'fa fa-arrow-left','class'=>'btn-primary'],
            ]);	
?>
<div class="row main-content">
  <div class="col-12 p-0">
<?= $this->form()->openTag($form); ?>
<div class="col-md-6">
	<div class="form-group form-group-default">
	  <?= $this->formLabel($form->get('amount_upto')); ?>
	  <?= $this->formElement($form->get('amount_upto')); ?>
	  <?= $this->formElementErrors($form->get('amount_upto')); ?>
	</div>
	<div class="form-group form-group-default">
		<?= $this->formLabel($form->get('tax_percentage')); ?>
		<div class="input-group">
			<?= $this->formElement($form->get('tax_percentage')); ?>
		<div class="input-group-append">
		<span class="input-group-text"><i class="fa fa-percent"></i></span>
		</div>
		</div>
		<?= $this->formElementErrors($form->get('tax_percentage')); ?>
	</div>
<?= $this->formElement($form->get('submit')); ?>
</div>
<?= $this->form()->closeTag(); ?>
    </div>
</div>