<?php
$title = $this->translate('Edit Contact');
$this->pageBreadcrumbs()->setTitle($title);
$this->headTitle($title);
$this->pageBreadcrumbs()->setItems([
            $this->translate('Contact')=>$this->url('contacts'),
            $this->translate('Edit')=>$this->url('contacts', ['action'=>'edit']),
            ]);
$this->mainMenu()->setActiveItemId('contacts');
$form->get('name')->setAttributes(['class'=>'form-control','placeholder'=>'Name']);
$form->get('designation')->setAttributes(['class'=>'form-control','placeholder'=>'Designation']);
$form->get('company')->setAttributes(['class'=>'form-control','placeholder'=>'Company']);
$form->get('city')->setAttributes(['class'=>'form-control','placeholder'=>'City']);
$form->get('address')->setAttributes(['class'=>'form-control','placeholder'=>'Address']);
$form->get('telephone')->setAttributes(['class'=>'form-control','placeholder'=>'Telephone']);
$form->get('email')->setAttributes(['class'=>'form-control','placeholder'=>'Email']);
$form->get('website')->setAttributes(['class'=>'form-control','placeholder'=>'Website']);
$form->get('submit')->setAttributes(['class'=>'btn btn-primary'])->setValue($this->translate('Update Contact'));
$form->prepare();
$this->PageActions()->setItems([
            ['label'=>'Back to Contacts','url'=>$this->url('contacts'),'icon'=>'fa fa-arrow-left','class'=>'btn-primary'],
            ]);
?>
<div class="row">
  <div class="col-md-12">
    <div class="card">
			<div class="card-header">
				<h4 class="card-title">Edit Contact</h4>
			</div>
        <?= $this->form()->openTag($form); ?>
			<div class="card-body row">
		
		<div class="col-md-6">
		<div class="form-group">
					<?= $this->formLabel($form->get('company')); ?>
					<?= $this->formElement($form->get('company')); ?>
					<?= $this->formElementErrors($form->get('company')); ?>
				</div>
        <div class="form-group">
            <?= $this->formLabel($form->get('name')); ?>
            <?= $this->formElement($form->get('name')); ?>
            <?= $this->formElementErrors($form->get('name')); ?>
        </div>
		<div class="form-group">
					<?= $this->formLabel($form->get('designation')); ?>
					<?= $this->formElement($form->get('designation')); ?>
					<?= $this->formElementErrors($form->get('designation')); ?>
				</div>
		<div class="form-group">
					<?= $this->formLabel($form->get('city')); ?>
					<?= $this->formElement($form->get('city')); ?>
					<?= $this->formElementErrors($form->get('city')); ?>
		</div>

		</div>
		<div class="col-md-6">
		<div class="form-group">
					<?= $this->formLabel($form->get('address')); ?>
					<?= $this->formElement($form->get('address')); ?>
					<?= $this->formElementErrors($form->get('address')); ?>
				</div>
		<div class="form-group input-group">
			<?= $this->formLabel($form->get('telephone')); ?>
			<div class="input-group">
				<div class="input-group-prepend">
				<div class="input-group-text"><i class="fa fa-phone"></i></div>
			</div>
				<?= $this->formElement($form->get('telephone')); ?>
				<?= $this->formElementErrors($form->get('telephone')); ?>
			</div>
		</div>

				
		<div class="form-group input-group">
			<?= $this->formLabel($form->get('email')); ?>
			<div class="input-group">
				<div class="input-group-prepend">
				<div class="input-group-text">@</div>
			</div>
				<?= $this->formElement($form->get('email')); ?>
				<?= $this->formElementErrors($form->get('email')); ?>
			</div>
		</div>
		
		<div class="form-group input-group">
			<?= $this->formLabel($form->get('website')); ?>
			<div class="input-group">
				<div class="input-group-prepend">
				<div class="input-group-text"><i class="fa fa-globe"></i></div>
			</div>
				<?= $this->formElement($form->get('website')); ?>
				<?= $this->formElementErrors($form->get('website')); ?>
			</div>
		</div>

       
    </div>   <div class="col-md-12">
   <div class="form-group">
			<?= $this->formElement($form->get('submit')); ?>
		</div>
		</div>
        <?= $this->form()->closeTag(); ?>
	</div>
	</div>
</div>