<!-- Modal Dialog -->
<div class="modal fade" id="confirmDelete" role="dialog" aria-labelledby="confirmDeleteLabel" aria-hidden="true">
<div class="modal-dialog modal-dialog-centered">
  <div class="modal-content">
    <div class="modal-header">
      <h4 class="modal-title"><?= $this->translate('Delete Permanently') ?></h4>
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    </div>
    <div class="modal-body">
      <p><?= $this->translate('Do you really want to delete these records? This process cannot be undone.') ?></p>
    </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-light" data-dismiss="modal"><?= $this->translate('Close') ?></button>
      <button type="button" class="btn btn-danger" id="confirm"> <?= $this->translate('Delete') ?></button>
    </div>
  </div>
</div>
</div>
