<?php
$title = $this->translate('Cards');
$this->headTitle($title);
$this->pageBreadcrumbs()->setTitle($title);
$this->mainMenu()->setActiveItemId('settings');
$this->pageBreadcrumbs()->setItems([
            $this->translate('Cards')=>$this->url('cards'),
            $this->translate('Listings')=>$this->url('cards'),
            ]);
$this->PageActions()->setItems([
            ['label'=>'Add Card','url'=>$this->url('cards', ['action'=>'add']),'icon'=>'fa fa-plus','class'=>'btn-primary'],
            ]);	
?>

<div class="row">
	<div class="col-md-12">
	<div class="card">
			<div class="card-header">
				<h4 class="card-title">Digital Cards</h4>
			</div>
			<div class="card-body">
	<form name="cards_form" method="post" action="#">
		<div class="form-row">
			<div class="form-group col-sm-3 d-flex">
			 <select class="form-control" name="s_user" data-init-plugin="select2">
				<option value="">Select User</option>
				<?php foreach ($this->users  as $user){ ?>
				<option <?= (isset($search_array['user'])&&($search_array['user']==$user->getEmail()))?'selected':''?> value="<?= $user->getEmail(); ?>"><?= $user->getFullName(); ?></option>
				<?php } ?>
     		  </select>
			  </div>
			<div class="col-sm-4 col-md-2 mg-t-10 mg-sm-t-0">
			  <button type="submit" class="btn btn-primary btn-block"><?= $this->translate('Filter Cards') ?></button>
			</div>
		</div>
	</form>
  
	 
	<div class="table-responsive">
	<table class="table table-responsive-md">
	<thead>
	<tr>
		<th><strong><?= $this->translate('Id') ?></strong></th>
		<th><strong><?= $this->translate('Action') ?></strong></th>
		<th><strong><?= $this->translate('Action Name') ?></strong></th>
		<th><strong><?= $this->translate('User') ?></strong></th>
		<th><strong><?= $this->translate('Date Created') ?></strong></th>
	</tr>
	</thead>	
	<tbody>
	
	</tbody>	
	</table>
	</div>
	<?= $this->partial('application/partial/paginator', ['paginator'=>$this->paginator,'search'=>base64_encode(serialize($search_array))]); ?>
</div> 
</div>
</div>
</div>

