<!DOCTYPE html>
<html lang="en-in">
   <head>
      <meta http-equiv="content-type" content="text/html; charset=UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
      <meta http-equiv="x-ua-compatible" content="ie=edge">
      
		<!-- Primary Meta Tags -->
		<title>Airkom Group</title>
		<meta name="title" content="Airkom Group">
		<meta name="description" content="Airkom Electronics Pvt. Ltd (AEPL) is a young and rapidly growing company & it is a part of the AIRKOM GROUP. ">
		<link href="<?= $this->basePath(); ?>/favicons/favicon.ico" rel="shortcut icon" type="image vnd.microsoft.icon">
		<!-- Open Graph / Facebook -->
		<meta property="og:type" content="website">
		<meta property="og:url" content="https://airkomgroup.com">
		<meta property="og:title" content="Airkom Group">
		<meta property="og:description" content="Airkom Electronics Pvt. Ltd (AEPL) is a young and rapidly growing company & it is a part of the AIRKOM GROUP. ">
		<meta property="og:image" content="https://airkomgroup.com/meta.jpg">

		<!-- Twitter -->
		<meta property="twitter:card" content="summary_large_image">
		<meta property="twitter:url" content="https://airkomgroup.com">
		<meta property="twitter:title" content="Airkom Group">
		<meta property="twitter:description" content="Airkom Electronics Pvt. Ltd (AEPL) is a young and rapidly growing company & it is a part of the AIRKOM GROUP. ">
		<meta property="twitter:image" content="https://airkomgroup.com/meta.jpg">

      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css">

      <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
	  
	  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.css" integrity="sha512-H9jrZiiopUdsLpg94A333EfumgUBpO9MdbxStdeITo+KEIMaNfHNvwyjjDJb+ERPaRS6DpyRlKbvPUasNItRyw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
   </head>
   <body>
   <style>
	   p, li, label, input{
		   font-size: .875rem;
	   }
	   p{
		   text-align:justify;
	   }
	   .carousel-indicators [data-bs-target] {
		   background-color:#000 !important;
	   }
   </style>
      <div class="container p-0 p-sm-2 p-md-3">
         <div class="row g-0">
            <div class="col-md-6 col-sm-10 mx-auto">
               <div class="card border-0 border-1 border-bottom border-dash-divider rounded-0" style="background-color:rgb(255,255,255);">
                  <div id="slider" class="carousel slide" data-bs-ride="carousel">
                     <div class="carousel-indicators mb-2">
                        <button type="button" data-bs-target="#slider" data-bs-slide-to="0" class="active" aria-label="Slide 1"></button>
                        <button type="button" data-bs-target="#slider" data-bs-slide-to="1" aria-label="Slide 2" class="" aria-current="true"></button>
                        <button type="button" data-bs-target="#slider" data-bs-slide-to="2" class="" aria-label="Slide 3"></button>
						<button type="button" data-bs-target="#slider" data-bs-slide-to="3" class="" aria-label="Slide 4"></button>
						<button type="button" data-bs-target="#slider" data-bs-slide-to="4" class="" aria-label="Slide 5"></button>
                     </div>
                     <div class="carousel-inner">
                        <div class="carousel-item active">
                           <a data-fancybox="banner" href="<?= $this->basePath(); ?>/banners/1.jpg">
								<img src="<?= $this->basePath(); ?>/banners/1.jpg" class="d-block w-100" alt="slide 1" />
							</a>
                        </div>
                        <div class="carousel-item">
                           <a data-fancybox="banner" href="<?= $this->basePath(); ?>/banners/2.jpg">
								<img src="<?= $this->basePath(); ?>/banners/2.jpg" class="d-block w-100" alt="slide 2" />
							</a>
                        </div>
						<div class="carousel-item">
                           <a data-fancybox="banner" href="<?= $this->basePath(); ?>/banners/3.jpg">
								<img src="<?= $this->basePath(); ?>/banners/3.jpg" class="d-block w-100" alt="slide 3" />
							</a>
                        </div>
						<div class="carousel-item">
                           <a data-fancybox="banner" href="<?= $this->basePath(); ?>/banners/4.jpg">
								<img src="<?= $this->basePath(); ?>/banners/4.jpg" class="d-block w-100" alt="slide 4" />
							</a>
                        </div>
						<div class="carousel-item">
                           <a data-fancybox="banner" href="<?= $this->basePath(); ?>/banners/5.jpg">
								<img src="<?= $this->basePath(); ?>/banners/5.jpg" class="d-block w-100" alt="slide 5" />
							</a>
                        </div>
                     </div>
                  </div>
                  <div class="card border-0 my-4">
                     <div class="row g-0">
                        <div class="col-4 p-1 align-self-center">
                           <img id="logo" class="img-fluid rounded-3" src="<?= $this->basePath(); ?>/images/logo-text.png">
                        </div>
                        <div class="col-8">
                           <div class="card-body ps-2 pe-1 py-0">
                              <h5 class="card-title mb-1" style=""><?= $settings->getCompanyName(); ?></h5>
                              <h6 class="card-subtitle fw-lighter my-1" style="font-size:0.875rem;">The Trusted Indian Brand For Power Solutions</h6>
                              <hr class="my-1">

                              <div class="d-flex align-items-start">
                                 <div>
                                    <h6 class="fw-bold mb-0 me-2"><?= $user->getFullName(); ?></h6>
                                    <p class="mb-0" style="line-height:13px;font-size:13px;"><?= $user->getDesignation(); ?></p>
                                 </div>
                                 <div class="contact-btn-group rounded-pill ms-1 px-1 pb-1">
                                    <a href="https://api.whatsapp.com/send?phone=<?= $user->getContactNo(); ?>" target="_blank" class="mx-1"><i class="fab fa-whatsapp align-middle" style="font-size:1.2rem;"></i></a>
                                    <a href="tel:+<?= $user->getContactNo(); ?>" target="_blank" class="ms-2 me-1"><i class="fas fa-phone align-middle"></i></a>
                                    <a href="mailto:<?= $user->getEmail(); ?>" target="_blank" class="mx-1 ms-2"><i class="fas fa-at align-middle"></i></a>
                                 </div>
                              </div>
                           </div>
                        </div>
                     </div>
                  </div>
				  
				  
				  
				  
                  <div class="d-flex justify-content-between cstm-btn">
                     <a id="vCardDownloadBtn" href="<?= $this->url('cards', ['action'=>'vcard','id'=>$user->getId()]); ?>" rel="noopener" class="btn btn-sm rounded-pill mmtc-btn shadow-sm flex-fill m-1">
                     <i class="fas fa-download i me-1"></i>Save Contact
                     </a>
                     <button data-bs-target="#qrcodemodal" data-bs-toggle="modal" class="btn btn-sm rounded-pill mmtc-btn shadow-sm flex-fill m-1">
                     <i class="fas fa-qrcode i me-1"></i>QR Code
                     </button>
                     <button class="btn btn-sm rounded-pill mmtc-btn shadow-sm px-2 flex-fill m-1" data-bs-target="#inquiry" data-bs-toggle="modal">Send Inquiry<i class="fas fa-angle-double-right i ms-2"></i></button>
                  </div>
                 
				 <div class="d-flex justify-content-between my-2 cstm-btn">                  
                     <a href="<?= $settings->getCatalog() ?>" download="<?= $settings->getCatalog() ?>" target="_blank" class="btn btn-sm rounded-pill mmtc-btn shadow-sm flex-fill m-1"><i class="fas fa-book i me-2"></i>Download Catalogue</a>
                     <button class="btn btn-sm rounded-pill mmtc-btn shadow-sm px-2 flex-fill m-1" data-bs-toggle="modal" data-bs-target="#shareModal"><i class="fas fa-paper-plane i me-1"></i>Share</button>
                  </div>
                  
				  
				  
				  
				  <div class="accordion accordion-flush border-top border-bottom" id="feat_accordion">
                     <div class="accordion-item">
                        <h2 class="accordion-header">
                           <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#fc_acc_address" aria-expanded="false">
                              <i class="fas fa-location-arrow me-2"></i> Contacts
                           </button>
                        </h2>
                        <div id="fc_acc_address" class="accordion-collapse collapse" data-bs-parent="#feat_accordion">
                           <div class="accordion-body px-1 py-2 p-sm-3">
                              <!-- Address -->
                              <div class="mb-3 mt-sm-2 no-iconbg">                               
                                 <a href="tel:+91<?= $user->getContactNo(); ?>" class="btn p-1 px-2 text-decoration-none" target="_blank"><i class="fas fa-phone-alt thm-color-bg-i rounded-circle me-2 align-middle" style="padding:0.3rem;"></i><span class="text-muted">+91 <?= $user->getContactNo(); ?></span></a>
                                 <a href="https://api.whatsapp.com/send?phone=<?= $user->getContactNo(); ?>" class="btn p-1 px-2 text-decoration-none" target="_blank"><i class="fab fa-whatsapp thm-color-bg-i rounded-circle me-2 align-middle" style="font-size:1.29rem;padding: 0.2rem 0.30rem;"></i><span class="text-muted">+91 <?= $user->getContactNo(); ?></span></a>
                                 <a href="mailto:<?= $user->getEmail(); ?>" class="btn p-1  text-decoration-none" target="_blank"><i class="fas fa-at thm-color-bg-i rounded-circle me-2 align-middle" style="padding:0.3rem;"></i><span class="text-muted"><?= $user->getEmail(); ?></span></a>
                              </div>
                              <div class="card position-relative bg-white my-2 p-1 rounded">
                                 <div class="row g-0 align-items-center">
                                    <div class="col-6 pt-1 rounded-3 text-center" style="background-color:#737272;">
                                       <a href="https://goo.gl/maps/K2a4MPWfHDeQyiL86" target="_blank" class="">
									   <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d15080.279800734525!2d73.0284433!3d19.104587!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x17d301c56b4b6e2e!2sAirkom%20Electronics%20Pvt%20Ltd%20-%20Head%20Office!5e0!3m2!1sen!2sin!4v1634337192448!5m2!1sen!2sin" width="100%" height="150" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
									   </a>
                                    </div>
                                    <div class="col-6">
                                       <div class="card-body text-dark">
                                          <p class="mb-2"><?= $settings->getAddress(); ?>, 
										  <br/>Mobile : <a style="text-decoration:none;color:inherit;font-weight:bold;" href="tel:+919323863400">+91 9323863400</a>
                                          </p>
                                       </div>
                                    </div>
                                 </div>
                              </div>
                           </div>
                        </div>
                     </div>
                     <div class="accordion-item">
                        <h2 class="accordion-header">
                           <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#fc_acc_about" aria-expanded="false">
                           <i class="fas fa-list-ul me-2"></i> About  
                           </button>
                        </h2>
                        <div id="fc_acc_about" class="accordion-collapse collapse" data-bs-parent="#feat_accordion">
                           <div class="accordion-body py-2 p-sm-3">
                              <?= $settings->getCompanyBrief(); ?>
                           </div>
                        </div>
                     </div>
                     <!-- Service -->
                     <div class="accordion-item">
                        <h2 class="accordion-header">
                           <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#fc_acc_srvpro" aria-expanded="false">
                           <i class="fas fa-cogs me-2"></i> Services / Products   
                           </button>
                        </h2>
                        <div id="fc_acc_srvpro" class="accordion-collapse collapse" data-bs-parent="#feat_accordion">
                           <div class="accordion-body py-2 p-sm-3">
                              <?= $settings->getServices(); ?>
                           </div>
                        </div>
                     </div>
                     <!-- Gallery -->
                     <div class="accordion-item">
                        <h2 class="accordion-header">
                           <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#fc_acc_gallery" aria-expanded="false">
                           <i class="fas fa-images me-2"></i> Gallery  
                           </button>
                        </h2>
                        <div id="fc_acc_gallery" class="accordion-collapse collapse" data-bs-parent="#feat_accordion">
                           <div class="accordion-body px-1 py-2 p-sm-3" id="imgGallery">
                              <div class="row g-0">
                                 
								 
                                    
											<div class="col-3 col-md-2 float-start mb-2 mb-sm-2 px-1 px-sm-2"><a data-fancybox="gallery" href="<?= $this->basePath(); ?>/gallery_images/6.jpg" data-caption=""><img class="img-fluid rounded bg-white shadow object-fit-cover-120 lozad" loading="lazy" src="<?= $this->basePath(); ?>/gallery_images/6.jpg"></a></div>
<div class="col-3 col-md-2 float-start mb-2 mb-sm-2 px-1 px-sm-2"><a data-fancybox="gallery" href="<?= $this->basePath(); ?>/gallery_images/7.jpg" data-caption=""><img class="img-fluid rounded bg-white shadow object-fit-cover-120 lozad" loading="lazy" src="<?= $this->basePath(); ?>/gallery_images/7.jpg"></a></div>
<div class="col-3 col-md-2 float-start mb-2 mb-sm-2 px-1 px-sm-2"><a data-fancybox="gallery" href="<?= $this->basePath(); ?>/gallery_images/8.jpg" data-caption=""><img class="img-fluid rounded bg-white shadow object-fit-cover-120 lozad" loading="lazy" src="<?= $this->basePath(); ?>/gallery_images/8.jpg"></a></div>
<div class="col-3 col-md-2 float-start mb-2 mb-sm-2 px-1 px-sm-2"><a data-fancybox="gallery" href="<?= $this->basePath(); ?>/gallery_images/9.jpg" data-caption=""><img class="img-fluid rounded bg-white shadow object-fit-cover-120 lozad" loading="lazy" src="<?= $this->basePath(); ?>/gallery_images/9.jpg"></a></div>
<div class="col-3 col-md-2 float-start mb-2 mb-sm-2 px-1 px-sm-2"><a data-fancybox="gallery" href="<?= $this->basePath(); ?>/gallery_images/9AB.jpg" data-caption=""><img class="img-fluid rounded bg-white shadow object-fit-cover-120 lozad" loading="lazy" src="<?= $this->basePath(); ?>/gallery_images/9AB.jpg"></a></div>
<div class="col-3 col-md-2 float-start mb-2 mb-sm-2 px-1 px-sm-2"><a data-fancybox="gallery" href="<?= $this->basePath(); ?>/gallery_images/9B.jpg" data-caption=""><img class="img-fluid rounded bg-white shadow object-fit-cover-120 lozad" loading="lazy" src="<?= $this->basePath(); ?>/gallery_images/9B.jpg"></a></div>
<div class="col-3 col-md-2 float-start mb-2 mb-sm-2 px-1 px-sm-2"><a data-fancybox="gallery" href="<?= $this->basePath(); ?>/gallery_images/9C.jpg" data-caption=""><img class="img-fluid rounded bg-white shadow object-fit-cover-120 lozad" loading="lazy" src="<?= $this->basePath(); ?>/gallery_images/9C.jpg"></a></div>
<div class="col-3 col-md-2 float-start mb-2 mb-sm-2 px-1 px-sm-2"><a data-fancybox="gallery" href="<?= $this->basePath(); ?>/gallery_images/9D.jpg" data-caption=""><img class="img-fluid rounded bg-white shadow object-fit-cover-120 lozad" loading="lazy" src="<?= $this->basePath(); ?>/gallery_images/9D.jpg"></a></div>
<div class="col-3 col-md-2 float-start mb-2 mb-sm-2 px-1 px-sm-2"><a data-fancybox="gallery" href="<?= $this->basePath(); ?>/gallery_images/10.jpg" data-caption=""><img class="img-fluid rounded bg-white shadow object-fit-cover-120 lozad" loading="lazy" src="<?= $this->basePath(); ?>/gallery_images/10.jpg"></a></div>
<div class="col-3 col-md-2 float-start mb-2 mb-sm-2 px-1 px-sm-2"><a data-fancybox="gallery" href="<?= $this->basePath(); ?>/gallery_images/11A.jpg" data-caption=""><img class="img-fluid rounded bg-white shadow object-fit-cover-120 lozad" loading="lazy" src="<?= $this->basePath(); ?>/gallery_images/11A.jpg"></a></div>
<div class="col-3 col-md-2 float-start mb-2 mb-sm-2 px-1 px-sm-2"><a data-fancybox="gallery" href="<?= $this->basePath(); ?>/gallery_images/11A.png" data-caption=""><img class="img-fluid rounded bg-white shadow object-fit-cover-120 lozad" loading="lazy" src="<?= $this->basePath(); ?>/gallery_images/11A.png"></a></div>
<div class="col-3 col-md-2 float-start mb-2 mb-sm-2 px-1 px-sm-2"><a data-fancybox="gallery" href="<?= $this->basePath(); ?>/gallery_images/11B.jpg" data-caption=""><img class="img-fluid rounded bg-white shadow object-fit-cover-120 lozad" loading="lazy" src="<?= $this->basePath(); ?>/gallery_images/11B.jpg"></a></div>
<div class="col-3 col-md-2 float-start mb-2 mb-sm-2 px-1 px-sm-2"><a data-fancybox="gallery" href="<?= $this->basePath(); ?>/gallery_images/13.jpg" data-caption=""><img class="img-fluid rounded bg-white shadow object-fit-cover-120 lozad" loading="lazy" src="<?= $this->basePath(); ?>/gallery_images/13.jpg"></a></div>
<div class="col-3 col-md-2 float-start mb-2 mb-sm-2 px-1 px-sm-2"><a data-fancybox="gallery" href="<?= $this->basePath(); ?>/gallery_images/14.jpg" data-caption=""><img class="img-fluid rounded bg-white shadow object-fit-cover-120 lozad" loading="lazy" src="<?= $this->basePath(); ?>/gallery_images/14.jpg"></a></div>
<div class="col-3 col-md-2 float-start mb-2 mb-sm-2 px-1 px-sm-2"><a data-fancybox="gallery" href="<?= $this->basePath(); ?>/gallery_images/15.jpg" data-caption=""><img class="img-fluid rounded bg-white shadow object-fit-cover-120 lozad" loading="lazy" src="<?= $this->basePath(); ?>/gallery_images/15.jpg"></a></div>
<div class="col-3 col-md-2 float-start mb-2 mb-sm-2 px-1 px-sm-2"><a data-fancybox="gallery" href="<?= $this->basePath(); ?>/gallery_images/16.jpg" data-caption=""><img class="img-fluid rounded bg-white shadow object-fit-cover-120 lozad" loading="lazy" src="<?= $this->basePath(); ?>/gallery_images/16.jpg"></a></div>
<div class="col-3 col-md-2 float-start mb-2 mb-sm-2 px-1 px-sm-2"><a data-fancybox="gallery" href="<?= $this->basePath(); ?>/gallery_images/17.jpg" data-caption=""><img class="img-fluid rounded bg-white shadow object-fit-cover-120 lozad" loading="lazy" src="<?= $this->basePath(); ?>/gallery_images/17.jpg"></a></div>
<div class="col-3 col-md-2 float-start mb-2 mb-sm-2 px-1 px-sm-2"><a data-fancybox="gallery" href="<?= $this->basePath(); ?>/gallery_images/19A.jpg" data-caption=""><img class="img-fluid rounded bg-white shadow object-fit-cover-120 lozad" loading="lazy" src="<?= $this->basePath(); ?>/gallery_images/19A.jpg"></a></div>
<div class="col-3 col-md-2 float-start mb-2 mb-sm-2 px-1 px-sm-2"><a data-fancybox="gallery" href="<?= $this->basePath(); ?>/gallery_images/19B.jpg" data-caption=""><img class="img-fluid rounded bg-white shadow object-fit-cover-120 lozad" loading="lazy" src="<?= $this->basePath(); ?>/gallery_images/19B.jpg"></a></div>
<div class="col-3 col-md-2 float-start mb-2 mb-sm-2 px-1 px-sm-2"><a data-fancybox="gallery" href="<?= $this->basePath(); ?>/gallery_images/19C.jpg" data-caption=""><img class="img-fluid rounded bg-white shadow object-fit-cover-120 lozad" loading="lazy" src="<?= $this->basePath(); ?>/gallery_images/19C.jpg"></a></div>
<div class="col-3 col-md-2 float-start mb-2 mb-sm-2 px-1 px-sm-2"><a data-fancybox="gallery" href="<?= $this->basePath(); ?>/gallery_images/19D.jpg" data-caption=""><img class="img-fluid rounded bg-white shadow object-fit-cover-120 lozad" loading="lazy" src="<?= $this->basePath(); ?>/gallery_images/19D.jpg"></a></div>
<div class="col-3 col-md-2 float-start mb-2 mb-sm-2 px-1 px-sm-2"><a data-fancybox="gallery" href="<?= $this->basePath(); ?>/gallery_images/1.jpg" data-caption=""><img class="img-fluid rounded bg-white shadow object-fit-cover-120 lozad" loading="lazy" src="<?= $this->basePath(); ?>/gallery_images/1.jpg"></a></div>
<div class="col-3 col-md-2 float-start mb-2 mb-sm-2 px-1 px-sm-2"><a data-fancybox="gallery" href="<?= $this->basePath(); ?>/gallery_images/1A.jpg" data-caption=""><img class="img-fluid rounded bg-white shadow object-fit-cover-120 lozad" loading="lazy" src="<?= $this->basePath(); ?>/gallery_images/1A.jpg"></a></div>
<div class="col-3 col-md-2 float-start mb-2 mb-sm-2 px-1 px-sm-2"><a data-fancybox="gallery" href="<?= $this->basePath(); ?>/gallery_images/1A.png" data-caption=""><img class="img-fluid rounded bg-white shadow object-fit-cover-120 lozad" loading="lazy" src="<?= $this->basePath(); ?>/gallery_images/1A.png"></a></div>
<div class="col-3 col-md-2 float-start mb-2 mb-sm-2 px-1 px-sm-2"><a data-fancybox="gallery" href="<?= $this->basePath(); ?>/gallery_images/1B.jpg" data-caption=""><img class="img-fluid rounded bg-white shadow object-fit-cover-120 lozad" loading="lazy" src="<?= $this->basePath(); ?>/gallery_images/1B.jpg"></a></div>
<div class="col-3 col-md-2 float-start mb-2 mb-sm-2 px-1 px-sm-2"><a data-fancybox="gallery" href="<?= $this->basePath(); ?>/gallery_images/2A.jpg" data-caption=""><img class="img-fluid rounded bg-white shadow object-fit-cover-120 lozad" loading="lazy" src="<?= $this->basePath(); ?>/gallery_images/2A.jpg"></a></div>
<div class="col-3 col-md-2 float-start mb-2 mb-sm-2 px-1 px-sm-2"><a data-fancybox="gallery" href="<?= $this->basePath(); ?>/gallery_images/3.jpg" data-caption=""><img class="img-fluid rounded bg-white shadow object-fit-cover-120 lozad" loading="lazy" src="<?= $this->basePath(); ?>/gallery_images/3.jpg"></a></div>
<div class="col-3 col-md-2 float-start mb-2 mb-sm-2 px-1 px-sm-2"><a data-fancybox="gallery" href="<?= $this->basePath(); ?>/gallery_images/4.jpg" data-caption=""><img class="img-fluid rounded bg-white shadow object-fit-cover-120 lozad" loading="lazy" src="<?= $this->basePath(); ?>/gallery_images/4.jpg"></a></div>
<div class="col-3 col-md-2 float-start mb-2 mb-sm-2 px-1 px-sm-2"><a data-fancybox="gallery" href="<?= $this->basePath(); ?>/gallery_images/5.jpg" data-caption=""><img class="img-fluid rounded bg-white shadow object-fit-cover-120 lozad" loading="lazy" src="<?= $this->basePath(); ?>/gallery_images/5.jpg"></a></div>

										
										

                                 
                              </div>
                           </div>
                        </div>
                     </div>
                     <!-- Video -->
                     <div class="accordion-item">
                        <h2 class="accordion-header">
                           <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#fc_acc_video" aria-expanded="false">
                           <i class="fas fa-video me-2"></i> Videos  
                           </button>
                        </h2>
                        <div id="fc_acc_video" class="accordion-collapse collapse" data-bs-parent="#feat_accordion" style="">
                           <div class="accordion-body px-1 py-2 p-sm-3" id="video">
                              <div class="row g-0">
                                 <div class="col-md-12 float-start mb-3 px-1 px-sm-2">
                                    <div>
										<iframe width="100%" height="315" src="https://www.youtube.com/embed/QT6lPMFODSA" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                                    </div>
                                 </div>
                                 
                              </div>
                           </div>
                        </div>
                     </div>
                     <!-- Taxes -->
                     <div class="accordion-item">
                        <h2 class="accordion-header">
                           <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#fc_acc_bank" aria-expanded="false">
                           <i class="fas fa-receipt me-2"></i> Tax Information   
                           </button>
                        </h2>
                        <div id="fc_acc_bank" class="accordion-collapse collapse" data-bs-parent="#feat_accordion" style="">
                           <div class="accordion-body px-1 py-2 p-sm-3" id="payment">
                              <div class="bg-white p-1 p-sm-2 p-md-3 p-lg-4 shadow mb-2 mb-sm-3 rounded">
                                 <?= $settings->getTaxInformation(); ?>
                              </div>
                           </div>
                        </div>
                     </div>
					 <!-- Payment -->
                     <div class="accordion-item">
                        <h2 class="accordion-header">
                           <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#fc_acc_bank" aria-expanded="false">
                           <i class="fas fa-money-bill-wave me-2"></i> Payments  
                           </button>
                        </h2>
                        <div id="fc_acc_bank" class="accordion-collapse collapse" data-bs-parent="#feat_accordion" style="">
                           <div class="accordion-body px-1 py-2 p-sm-3" id="payment">
                              <div class="bg-white p-1 p-sm-2 p-md-3 p-lg-4 shadow mb-2 mb-sm-3 rounded">
                                 <?= $settings->getPayment(); ?>
                              </div>
                           </div>
                        </div>
                     </div>
                  </div>
                  <!-- Social and Weblinks -->
                  <div class="d-flex flex-wrap justify-content-evenly my-3 px-2 text-center" style="min-height: 27px;" id="socials">
                     <a href="<?= $settings->getWebsite(); ?>" class="card-link btn mb-1 p-1" target="_blank"><i class="fas fa-globe" style="font-size:27px;"></i></a>
                     <a href="<?= $settings->getFacebook(); ?>" target="_blank" class="card-link mb-1 p-1 btn"><i class="fab fa-facebook" style="font-size:27px;"></i></a>
                     <a href="<?= $settings->getInstagram(); ?>" target="_blank" class="card-link mb-1 p-1 btn"><i class="fab fa-instagram " style="font-size:27px;"></i></a>
                     <a href="<?= $settings->getLinkedin(); ?>" target="_blank" class="card-link mb-1 p-1 btn"><i class="fab fa-linkedin" style="font-size:27px;"></i></a>
                     <a href="<?= $settings->getYoutube(); ?>" target="_blank" class="card-link mb-1 p-1 btn"><i class="fab fa-youtube" style="font-size:27px;"></i></a>
                  </div>
               </div>

            </div>
         </div>
      </div>
	  
	  
	  
	  

     

	 <!-- Modal Inquiry-->
      <div class="modal fade" id="inquiry" tabindex="-1" role="dialog" aria-labelledby="inquiry" aria-hidden="true">
         <div class="modal-dialog box-shadow modal-fullscreen-sm-down" role="document">
            <div class="modal-content border-0">
               <div class="modal-header box-shadow">
                  <h5 class="modal-title" id="inquiryTitle">Send Inquiry</h5>
                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
               </div>
               <div class="modal-body border-0">
                  <form action="<?= $this->url('cards', ['action'=>'addContact','id'=>$user->getId()]); ?>" method="post">

                     <div id="contact-form" class="form-container" data-form-container="">
                        <div class="input-container">
                           <div class="row g-0">
                              <label for="name" class="form-label">Full Name</label>
                              <input class="form-control mb-3" type="text" name="name" data-min-length="2" placeholder="Full Name" />
                           </div>
                           <div class="row g-0">
                              <label for="designation" class="form-label">Designation</label>
                              <input class="form-control mb-3" type="text" name="designation" placeholder="Designation" required="" />
                           </div>
                           <div class="row g-0">
                              <label for="company" class="form-label">Company</label>
                              <input class="form-control mb-3" type="text" name="company" placeholder="Company" required="" />
                           </div>
						   <div class="row g-0">
                              <label for="telephone" class="form-label">Telephone</label>
                              <input class="form-control mb-3" type="text" name="telephone" placeholder="Telephone" required="" />
                           </div>
						   <div class="row g-0">
                              <label for="email" class="form-label">Email Address</label>
                              <input class="form-control mb-3" type="email" name="email" placeholder="Email Address" required="" />
                           </div>
                           <div class="row submit-row">
                              <div class="w-100 text-center">
                                 <button type="submit" class="btn py-1 mt-4 px-3 rounded submit-form btn-primary">Submit</button>
                              </div>
                           </div>
                        </div>
                     </div>
                  </form>
               </div>
            </div>
         </div>
      </div>
     

	 <!-- Modal Share-->
      <div class="modal fade" id="shareModal" tabindex="-1" role="dialog" aria-labelledby="shareModal" aria-hidden="true">
         <div class="modal-dialog box-shadow" role="document">
            <div class="modal-content border-0">
               <div class="modal-header box-shadow">
                  <h5 class="modal-title" id="shareTitle">Share</h5>
                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
               </div>
               <div class="modal-body bg-light-lite-85 border-0">
                  <div class="addthis_inline_share_toolbox"></div> 
               </div>
            </div>
         </div>
      </div>
      
	  <!-- Modal QR Code -->
      <div class="modal fade" id="qrcodemodal" tabindex="-1" role="dialog" aria-labelledby="qrcodemodal" aria-hidden="true">
         <div class="modal-dialog box-shadow" role="document">
            <div class="modal-content border-0">
               <div class="modal-header box-shadow">
                  <h5 class="modal-title" id="qrTitle">Scan QR Code</h5>
                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
               </div>
               <div class="modal-body border-0">

                  <div class="w-75 my-3 mx-auto">
                     <img class="img-fluid mx-auto d-block px-4" src="<?= $this->basePath(); ?>/meta/qrcode.png" alt="Airkom Group Logo">
                  </div>
                  <div class="col-md-6 mx-auto text-center">
                     <h4 class="text-dark">Scan QR Code</h4>
                     <a class="btn btn-success btn-sm mt-2" href="<?= $this->basePath(); ?>/meta/qrcode.png" download="Airkom Group QR Code">Download QR Code</a> 
                  </div>
               </div>
            </div>
         </div>
      </div>
     
	 
<style>
.cstm-btn .rounded-pill {
    background: linear-gradient(180deg,#9cdeff 0%,#0093dd 49%,#0093dd 57.21107823014668%,#00aaff 100%);
    color: #fff;
    text-transform: uppercase;
    font-weight: bold;
}
.accordion-item i{
	background: #0093dd;
	color: #fff;
	border-radius: 50%;
	width: 30px;
	height: 30px;
	text-align: center;
	line-height: 30px;
	padding: 0;
	margin: 0;
}
.accordion-item .no-iconbg i{
	background: none;
	color: #000;
	width:20px;
	height:20px;
	padding: 0 !important;
	line-height: 20px;
}
.fa-whatsapp{
	color:#1c9c10;
}
.fa-phone{
	color:#1c9c10;
}
.fa-at{
	color:#1c9c10;
}
.fa-globe{
	color:#044284;
}
.fa-facebook{
	color:#395693;
}
.fa-instagram {
	color:#cb0061;
}
.fa-linkedin{
	color:#0270ad;
}
.fa-youtube{
	color:#f70000;
}
</style>	 
	<!-- Bootstrap -->
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js"></script>
	<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-616a17f0b9d81773"></script> 

	  <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
	        <script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.js" integrity="sha512-uURl+ZXMBrF4AwGaWmEetzrd+J5/8NRkWAvJx5sbPSSuOb0bZLqf+tOzniObO00BjHa/dD7gub9oCGMLPQHtQA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
	  
	  <script>
	  $('[data-fancybox="gallery"]').fancybox({
	// Options will go here
});
</script>
   </body>
</html>

