<?php
$title = $this->translate('Change Password');
$this->headTitle($title);
$this->pageBreadcrumbs()->setTitle($title);
$this->mainMenu()->setActiveItemId('settings');

$this->pageBreadcrumbs()->setItems([
           $this->translate('Home')=>$this->url('home'),
           $this->translate('Manage Users')=>$this->url('users'),
           $this->translate('Change Password') =>$this->url('users', ['action'=>'change-password', 'id'=>$user->getId()])
            ]);

// $form->get('old_password')->setAttributes([
    // 'class'=>'form-control',
    // 'placeholder'=>'Enter old password'
    // ]);

$form->get('new_password')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Enter new password'
    ]);

$form->get('confirm_new_password')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Re-enter new password',

    ]);

$form->get('submit')->setAttributes(['class'=>'btn btn-primary']);

$form->prepare();

$this->PageActions()->setItems([
            ['label'=>'Back to Users','url'=>$this->url('users'),'icon'=>'arrow-left','class'=>'btn-primary'],
            ]);	
?>



<div class="row">
  <div class="col-12 col-md-6">
    <div class="card">
	<?= $this->form()->openTag($form); ?>

<div class="card-body">
    <div class="form-group">
        <?= $this->formLabel($form->get('new_password')); ?>
        <?= $this->formElement($form->get('new_password')); ?>
        <?= $this->formElementErrors($form->get('new_password')); ?>
    </div>

    <div class="form-group">
        <?= $this->formLabel($form->get('confirm_new_password')); ?>
        <?= $this->formElement($form->get('confirm_new_password')); ?>
        <?= $this->formElementErrors($form->get('confirm_new_password')); ?>
    </div>

    <?= $this->formElement($form->get('csrf')); ?>

    <?= $this->formElement($form->get('submit')); ?>
</div>
    <?= $this->form()->closeTag(); ?>
      </div>
      </div>

</div>
