<?php
$title = $this->translate('Thank You');
$this->mainMenu()->setActiveItemId('settings');
$this->headTitle($title);
?>

<div class="row main-content">	
  <div class="col-xl-12 col-lg-12 ">
        <div class="page-header ">
          <h1 class="title"><?= $this->escapeHtml('Thank You'); ?></h1>
        </div>
		<div class="col-md-offset-4 col-md-5">
		<h1><?= $this->translate('Reset Password') ?></h1>

		<?php if ($id=='sent'): ?>
		<p>
			<?= $this->translate('A password reset link has been sent to your email address') ?>.
		</p>
		<?php elseif ($id=='invalid-email'): ?>
		<p>
			<?= $this->translate('There is no user with such an email') ?>.
		</p>
		<?php elseif ($id=='set'): ?>
		<p>
			<?= $this->translate('Your new password has been set successfully') ?>.
		</p>
		<p>
			<?= $this->translate('Return to') ?> <a rel="nofollow" href="<?= $this->url('login'); ?>"><?= $this->translate('login page') ?></a>.
		</p>
		<?php elseif ($id=='failed'): ?>

			<?= $this->translate('Invalid reset key or it may have expired. Please return') ?>
			<a href="<?= $this->url('reset-password') ?>"><?= $this->translate('here') ?></a> <?= $this->translate('and try reset your password again') ?>.
		</p>
		<?php endif; ?>
		</div>
    </div>
</div>
