<?php
$title = $this->translate('Reset Password');
$this->headTitle($title);
$this->mainMenu()->setActiveItemId('settings');
$form->get('email')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Email address'
    ]);
$form->get('submit')->setAttributes([
    'class'=>'btn btn-large btn-primary'
    ]);
$form->prepare();
?>
 <div class="row justify-content-center h-100 align-items-center">
<div class="col-md-6">
<div class="authincation-content">
	<div class="row no-gutters">
		<div class="col-xl-12">
			<div class="auth-form">
				<div class="text-center mb-3">
					<a href="<?= $this->url('home') ?>"><img style="max-width:270px;" src="<?= $this->basePath('images/logo-white.png') ?>"></a>
				</div>
				<h4 class="text-center mb-4 text-white">Reset Password</h4>
				<form id="form-login" method="post">
					<div class="form-group">
						<?= $this->formLabel($form->get('email')); ?>
						<?= $this->formElement($form->get('email')); ?>
					</div>
					<div class="text-center mb-2">
						<button type="submit" class="btn bg-white text-primary btn-block"><?= $this->translate('Submit') ?></button>
					</div>
					<div class="text-center">
						<a href="<?= $this->url('home') ?>" class="btn bg-white text-primary btn-block"><?= $this->translate('Back to login') ?></a>
					</div>
				</form>

			</div>
		</div>
	</div>
</div>					
</div>					
</div>	
