<?php
$title = $this->translate('Set New Password');
$this->headTitle($title);
$this->mainMenu()->setActiveItemId('settings');
$this->pageBreadcrumbs()->setItems([
            $this->translate('Home')=>$this->url('home'),
           $this->translate('Set New Password')=>$this->url('set-password')
            ]);
$form->get('new_password')->setAttributes(array(
    'class'=>'form-control', 
    'placeholder'=>'Type New Password'
    ));
$form->get('confirm_new_password')->setAttributes(array(
    'class'=>'form-control', 
    'placeholder'=>'Confirm New Password'
    ));
$form->get('submit')->setAttributes(array(
    'class'=>'btn btn-primary'
    ));
$form->prepare();
?>
<div class="row main-content">
  <div class="col-12">  
		<div class="page-header ">
		  <h1 class="title"><?= $this->escapeHtml('Reset Password'); ?></h1>          
		</div>
		<div class="col-md-offset-4 col-md-4">
			<?= $this->form()->openTag($form); ?>
			<h2><?= $this->translate('Set New Password') ?></h2>
			<p><?= $this->translate('Enter your new password in the form below') ?></p>
			<div class="form-group">
				<?= $this->formLabel($form->get('new_password')); ?>
				<?= $this->formElement($form->get('new_password')); ?>
				<?= $this->formElementErrors($form->get('new_password')); ?>                              
			</div>
			<div class="form-group">
				<?= $this->formLabel($form->get('confirm_new_password')); ?>
				<?= $this->formElement($form->get('confirm_new_password')); ?>
				<?= $this->formElementErrors($form->get('confirm_new_password')); ?>   
			</div>    
			<?= $this->formElement($form->get('submit')); ?>
			<?= $this->formElement($form->get('csrf')); ?>
			<?= $this->form()->closeTag(); ?>
		</div>		
</div>  
</div>