<?php
$title = $this->translate('Pipeline');
$this->headTitle($title);
$this->pageBreadcrumbs()->setTitle($title);
$this->mainMenu()->setActiveItemId('pipeline');
$this->pageBreadcrumbs()->setItems([
            $this->translate('Pipeline')=>$this->url('pipeline'),
            $this->translate('Manage')=>$this->url('pipeline'),
            ]);
			
$this->headScript()->appendFile($this->basePath() . '/js/plugins-init/dragula.min.js', 'text/javascript'); 
$this->headScript()->appendFile($this->basePath() . '/js/dragula.js', 'text/javascript'); 
?>

<div class="row">
<div class="col-md-12">
	<form id="user_filter_form" method="post" action="<?= $this->url('pipeline'); ?>">
		<div class="form-row">
			<div class="form-group col-sm-4">
			  <input class="form-control" id="s_pipeline" name="s_pipeline" value="<?= $_POST['s_pipeline'] ?? '' ?>" placeholder="Search Pipeline"/>
			  </div>
			<div class="col-sm-3 mg-t-10 mg-sm-t-0">
			  <button type="submit" class="btn btn-primary btn-block mg-b-10">Search</button>
			</div>
		</div>
	</form>
</div>

  <div class="col-12">
	<div class="drag-container">
		<ul class="drag-list">
			<?php 
			function getAbbr($var){
				$words = explode(" ", $var);
				$acronym = "";
				
				if(!is_array($words)){
					$acronym = $var[0];
					return $acronym;
				}
                $i = 0;
				foreach ($words as $w) {
                    if($i == 2){
                        continue;
                    }
                if($w[0]){
				  $acronym .= $w[0];
                }
                  $i++;
				}
				return $acronym;
			}
			
			
			?>
			
			
			<?php 
			$i = 1;
			foreach ($stages as $s){ ?>
			<li data-stage="<?= $s->getId(); ?>" class="drag-column">
				<span class="drag-column-header">
					<h2><?= $s->getName(); ?></h2>
				</span>
					
				<div class="drag-options" id="options<?= $i ?>"></div>
				
				<ul class="drag-inner-list" id="<?= $i ?>">
				<?php 
					foreach ($pipeline as $p){ 
					 if($p['stage'] != $s->getId()) {continue;}
					 $cname = $this->ContactDetail()->getCompanyName($p['contact']);
					 $name = $this->ContactDetail()->getName($p['contact']);
				?>
					<li class="drag-item" data-user="<?= $user ?>" data-id="<?= $p['id'] ?>" data-spt="<?= $p['sptId'] ?>">
					<div class="timeline-panel">
						<div class="media mr-2">
						
							<span class="media-info"><?= $p['sptId']; ?></span>
						</div>
						<div class="media-body">
							<h5 class="mb-1"><?= $cname; ?></h5>
							<small class="d-block"><?= $name; ?></small>
							<!--<small class="d-block"> ID:<?= $p['id']; ?> |SPT ID:<?= $p['sptId']; ?> | Contact:<?= $p['contact']; ?></small>-->
						</div>
					</div>
					</li>
					<?php } ?>
				</ul>
			</li>
			
			<?php 
			$i++;
			} ?>
			
		</ul>
	</div>
	</div>
	</div>
<style>
.drag-inner-list{
	max-height: 500px;
	overflow-y: scroll;
}
</style>