<?php
$title = $this->translate('Dashboard');
$this->headTitle($title);
$this->mainMenu()->setActiveItemId('dashboard');
$this->pageBreadcrumbs()->setTitle('DCR Report');
$this->headLink()->appendStylesheet($this->basePath() . '/vendor/datatables/css/jquery.dataTables.min.css'); 
$this->headScript()->appendFile($this->basePath() . '/vendor/datatables/js/jquery.dataTables.min.js', 'text/javascript'); 
$this->headScript()->appendFile($this->basePath() . '/vendor/datatables/js/dataTables.buttons.min.js', 'text/javascript'); 
$this->headScript()->appendFile($this->basePath() . '/vendor/datatables/js/buttons.colVis.min.js', 'text/javascript'); 
$this->headScript()->appendFile($this->basePath() . '/vendor/datatables/js/buttons.print.min.js', 'text/javascript'); 
$this->headScript()->appendFile($this->basePath() . '/js/plugins-init/datatables.init.js'); 
$this->PageActions()->setItems([
            ['label'=>'Back to Dashboard','url'=>$this->url('dashboard'),'icon'=>'fa fa-arrow-left','class'=>'btn-primary'],
            ]);
?>
<?php if(isset($data)) { ?>
<div class="row dashboard">
<div class="col-xl-12">
<div class="card">
<div class="card-header d-sm-flex d-block border-0 pb-0">
<div class="col-xs-12 col-sm-6">
							<h4 id="reportuser" class="fs-20 text-black"><?= gettype($user) == 'object'?$user->getFullName():'All Users'; ?></h4>
							<span id="reportdetails" class="fs-16"><b>Branch:</b> <?= gettype($user) == 'object'? $this->UserDetail()->getBranch($user->getBranch()):'All Branches'; ?> <b>Date:</b> <?= $daterange; ?></span>
						</div>	
						<?php if (isset($ov) && !empty($ov)){ ?>
							<div class="col-xs-12 col-sm-6">
								<div class="d-flex flex-wrap text-black fs-12 mt-4">
									<?php $colors = ['#1EAAE7','#FF7A30','#2BC155','#FF2E2E']; ?>
									<?php foreach ($ov as $k => $v) { ?>
										<div class="col-6 mb-3">
											<svg class="mr-2" width="19" height="19" viewBox="0 0 19 19" fill="none" xmlns="http://www.w3.org/2000/svg">
												<rect width="19" height="19" rx="9.5" fill="<?= $colors[$k] ?>"></rect>
											</svg>
											<?= $v['calltype']; ?> (₹ <?= number_format($v['ov'],0); ?>)
										</div>
									<?php } ?>
								</div>
							</div>
						<?php } ?>
</div>
<div class="card-body pb-0">
<div class="table-responsive">
	<table id="datatable" class="display min-w850 dataTable" style="width:100%">
		<thead>
			<tr>
				<th>Visit date</th>
				<th>DCR No.</th>
				<th>Call Type</th>
				<th>Call Count</th>
				<th>Name</th>
				<th>City</th>
				<th>Company</th>
				<th>Telephone</th>
				<th>Product</th>
				<th>Model</th>
				<th>Quantity</th>
				<th>Order Value</th>
				<th>Sales Stage</th>
				<th>Next Action</th>
				<th>Remarks</th>
				<th>Bike KM Start</th>
				<th>Bike KM End</th>
				<th>Distance Travelled</th>
				<th>Amount One</th>
				<th>Travel Mode</th>
				<th>Amount Two</th>
				<th>Date Created</th>
			</tr>
		</thead>
		<tbody>
		<?php foreach ($data as $s) { ?>
			<tr>
				<td><?= $s['visitDate'] ;?></td>
				<td><?= $s['dcrNo'] ;?></td>
				<td><?= $s['callType'] ;?></td>
				<td><?= $s['callCount'] ;?></td>
				<td><?= $s['name'] ;?></td>
				<td><?= $s['city'] ;?></td>
				<td><?= $s['company'] ;?></td>
				<td><?= $s['telephone'] ;?></td>
				<td><?= $s['productId'] ;?></td>
				<td><?= $s['productModel'] ;?></td>
				<td><?= $s['quanitity'] ;?></td>
				<td>₹ <?= number_format($s['orderValue'], 0);?></td>
				<td><?= $s['salesStage'] ;?></td>
				<td><?= $s['nextAction'] ;?></td>
				<td><?= $s['remarks'] ;?></td>
				<td><?= $s['bikeKmReadingStart'] ;?></td>
				<td><?= $s['bikeKmReadingEnd'] ;?></td>
				<td><?= $s['distanceTravelled'] ;?></td>
				<td><?= $s['amountOne'] ;?></td>
				<td><?= $s['travelMode'] ;?></td>
				<td><?= $s['amountTwo'] ;?></td>
				<td><?= $s['dateCreated'] ;?></td>
			</tr>
		<?php } ?>
		</tbody>
	</table>
</div>
</div>
</div>
</div>
</div>
<?php } ?>