<?php
$title = $this->translate('Dashboard');
$this->headTitle($title);
$this->mainMenu()->setActiveItemId('dashboard');
$this->pageBreadcrumbs()->setTitle('SPT Report');
$this->headLink()->appendStylesheet($this->basePath() . '/vendor/datatables/css/jquery.dataTables.min.css'); 
$this->headScript()->appendFile($this->basePath() . '/vendor/datatables/js/jquery.dataTables.min.js', 'text/javascript'); 
$this->headScript()->appendFile($this->basePath() . '/vendor/datatables/js/dataTables.buttons.min.js', 'text/javascript'); 
$this->headScript()->appendFile($this->basePath() . '/vendor/datatables/js/buttons.colVis.min.js', 'text/javascript'); 
$this->headScript()->appendFile($this->basePath() . '/vendor/datatables/js/buttons.print.min.js', 'text/javascript'); 
$this->headScript()->appendFile($this->basePath() . '/js/plugins-init/datatables.init.js'); 

$this->PageActions()->setItems([
            ['label'=>'Back to Dashboard','url'=>$this->url('dashboard'),'icon'=>'fa fa-arrow-left','class'=>'btn-primary'],
            ]);
?>
<?php if(isset($data)) { ?>
<div class="row dashboard">
	<div class="col-xl-12">
				<div class="card">
					<div class="card-header d-sm-flex d-block border-0 pb-0">
						<div class="col-xs-12 col-sm-6">
							<h4 id="reportuser" class="fs-20 text-black"><?= gettype($user) == 'object'?$user->getFullName():'All Users'; ?></h4>
							<span id="reportdetails" class="fs-16"><b>Branch:</b> <?= gettype($user) == 'object'? $this->UserDetail()->getBranch($user->getBranch()):'All Branches'; ?> <b>Date:</b> <?= $daterange; ?></span>
						</div>
						
						<?php if (isset($fbv) && !empty($fbv)){ ?>
							<div class="col-xs-12 col-sm-6">
								<div class="d-flex flex-wrap text-black fs-12 mt-4">
									<?php $colors = ['#1EAAE7','#FF7A30','#2BC155','#FF2E2E']; ?>
									<?php foreach ($fbv as $k => $f) { ?>
										<div class="col-6 mb-3">
											<svg class="mr-2" width="19" height="19" viewBox="0 0 19 19" fill="none" xmlns="http://www.w3.org/2000/svg">
												<rect width="19" height="19" rx="9.5" fill="<?= $colors[$k] ?>"></rect>
											</svg>
											<?= $f['stage']; ?> (₹ <?= number_format($f['fbv'],0); ?>)
										</div>
									<?php } ?>
								</div>
							</div>
						<?php } ?>
					</div>
					<div class="card-body pb-0">
					 <div class="table-responsive">
                                    <table id="datatable" class="display min-w850 dataTable" style="width:100%">
                                        <thead>
                                            <tr>
												<th>Stage</th>
												<th>Prospect</th>
												<th>Lead Source</th>
												<th>Executive</th>
												<th>Offer No</th>
												<th>Sales Stage</th>
												<th>Product Series</th>
												<th>Actual Product</th>
												<th>FBV</th>
												<th>Quantity</th>
												<th>Exp. Close Date</th>
												<th>Expected Month</th>
												<th>Close Probability</th>
												<th>Next Action</th>
												<th>Last Con. Date</th>
												<th>Remarks</th>
												<th>Contacted Type</th>
												<th>Contact Name</th>
												<th>Designation</th>
												<th>City</th>
												<th>Telephone</th>
												<th>Email</th>
												<th>Website</th>
												<th>Date Created</th>
                                            </tr>
                                        </thead>
                                        <tbody>
										<?php foreach ($data as $s) { ?>
                                            <tr>
                                                <td><?= $s['stage'] ;?></td>
                                                <td><?= $s['propectName'] ;?></td>
                                                <td><?= $s['leadSource'] ;?></td>
                                                <td><?= $s['executive'] ;?></td>
                                                <td><?= $s['offerNo'] ;?></td>
                                                <td><?= $s['salesStage'] ;?></td>
                                                <td><?= $s['productSeries'] ;?></td>
                                                <td><?= $s['actualProduct'] ;?></td>
                                                <td>₹ <?= number_format($s['forecastedBookingValue'], 0);?></td>
                                                <td><?= $s['quanitity'] ;?></td>
                                                <td><?= $s['expectedCloseDate'] ;?></td>
                                                <td><?= $s['expectedMonth'] ;?></td>
                                                <td><?= $s['closeProbability'] ;?></td>
                                                <td><?= $s['nextAction'] ;?></td>
                                                <td><?= $s['lastContactedDate'] ;?></td>
                                                <td><?= $s['remarks'] ;?></td>
                                                <td><?= $s['contactedType'] ;?></td>
                                                <td><?= $s['contact'] ;?></td>
                                                <td><?= $s['designation'] ;?></td>
                                                <td><?= $s['city'] ;?></td>
                                                <td><?= $s['telephone'] ;?></td>
                                                <td><?= $s['email'] ;?></td>
                                                <td><?= $s['website'] ;?></td>
                                                <td><?= $s['dateCreated'] ;?></td>
                                            </tr>
										<?php } ?>
                                        </tbody>
                                    </table>
                                </div>
					</div>
				</div>
			</div>
</div>
<?php } ?>