<?php
$title = $this->translate('Add SPT');
$this->pageBreadcrumbs()->setTitle($title);
$this->headTitle($title);
$this->pageBreadcrumbs()->setItems([
            $this->translate('SPT')=>$this->url('spt'),
            $this->translate('Add')=>$this->url('spt', ['action'=>'add']),
            ]);
$this->mainMenu()->setActiveItemId('spt');
$form->get('stage')->setAttributes(['class'=>'form-control','placeholder'=>'Stage']);
$form->get('propect_name')->setAttributes(['class'=>'form-control','placeholder'=>'Propect Name']);
$form->get('lead_source')->setAttributes(['class'=>'form-control','placeholder'=>'Lead Source']);
$form->get('executive')->setAttributes(['class'=>'form-control','placeholder'=>'Executive']);
$form->get('offer_no')->setAttributes(['class'=>'form-control','placeholder'=>'Offer No']);
$form->get('sales_stage')->setAttributes(['class'=>'form-control','placeholder'=>'Sales Stage']);
$form->get('product_series')->setAttributes(['class'=>'form-control','placeholder'=>'Product Series']);
$form->get('product_model')->setAttributes(['class'=>'form-control','placeholder'=>'Product Model']);
$form->get('actual_product')->setAttributes(['class'=>'form-control','placeholder'=>'Actual Product']);
$form->get('forecasted_booking_value')->setAttributes(['class'=>'form-control','placeholder'=>'Forecasted Booking Value']);
$form->get('quanitity')->setAttributes(['class'=>'form-control','placeholder'=>'Quantity']);
$form->get('expected_close_date')->setAttributes(['class'=>'form-control input-datepicker','placeholder'=>'Expected Close Date']);
$form->get('expected_month')->setAttributes(['class'=>'form-control','placeholder'=>'Expected Month']);
$form->get('close_probability')->setAttributes(['class'=>'form-control','placeholder'=>'Close Probability']);
$form->get('next_action')->setAttributes(['class'=>'form-control','placeholder'=>'Next Action']);
$form->get('last_contacted_date')->setAttributes(['class'=>'form-control input-datepicker','placeholder'=>'Last Contacted Date']);
$form->get('remarks')->setAttributes(['class'=>'form-control','placeholder'=>'Remarks']);
$form->get('contacted_type')->setAttributes(['class'=>'form-control','placeholder'=>'Contacted Type']);
$form->get('contact_id')->setAttributes(['class'=>'form-control','placeholder'=>'Contact']);


$form->get('submit')->setAttributes(['class'=>'btn btn-primary'])->setValue($this->translate('Save SPT'));
$form->prepare();
$this->PageActions()->setItems([
            ['label'=>'Back to SPT','url'=>$this->url('spt'),'icon'=>'arrow-left','class'=>'btn-primary'],
            ]);
?>
<div class="row">
  <div class="col-md-12">
    <div class="card">
		<div class="card-header">
			<h4 class="card-title">Add SPT</h4>
		</div>
		<?= $this->form()->openTag($form); ?>
		<div class="card-body row">
		<div class="col-md-6">
			<div class="form-group">
            <?= $this->formLabel($form->get('stage')); ?>
            <?= $this->formElement($form->get('stage')); ?>
            <?= $this->formElementErrors($form->get('stage')); ?>
        </div>
		<div class="form-group">
			<?= $this->formLabel($form->get('propect_name')); ?>
			<?= $this->formElement($form->get('propect_name')); ?>
			<?= $this->formElementErrors($form->get('propect_name')); ?>
		</div>
		<div class="form-group">
			<?= $this->formLabel($form->get('lead_source')); ?>
			<?= $this->formElement($form->get('lead_source')); ?>
			<?= $this->formElementErrors($form->get('lead_source')); ?>
		</div>
		<div class="form-group">
			<?= $this->formLabel($form->get('executive')); ?>
			<?= $this->formElement($form->get('executive')); ?>
			<?= $this->formElementErrors($form->get('executive')); ?>
		</div>
		<div class="form-group">
			<?= $this->formLabel($form->get('offer_no')); ?>
			<?= $this->formElement($form->get('offer_no')); ?>
			<?= $this->formElementErrors($form->get('offer_no')); ?>
		</div>
		<div class="form-group">
			<?= $this->formLabel($form->get('sales_stage')); ?>
			<?= $this->formElement($form->get('sales_stage')); ?>
			<?= $this->formElementErrors($form->get('sales_stage')); ?>
		</div>
		<div class="form-group">
			<?= $this->formLabel($form->get('product_series')); ?>
			<?= $this->formElement($form->get('product_series')); ?>
			<?= $this->formElementErrors($form->get('product_series')); ?>
		</div>
		<div class="form-group">
			<?= $this->formLabel($form->get('product_model')); ?>
			<?= $this->formElement($form->get('product_model')); ?>
			<?= $this->formElementErrors($form->get('product_model')); ?>
		</div>
		<div class="form-group">
			<?= $this->formLabel($form->get('actual_product')); ?>
			<?= $this->formElement($form->get('actual_product')); ?>
			<?= $this->formElementErrors($form->get('actual_product')); ?>
		</div>
		<div class="form-group">
			<?= $this->formLabel($form->get('forecasted_booking_value')); ?>
			<?= $this->formElement($form->get('forecasted_booking_value')); ?>
			<?= $this->formElementErrors($form->get('forecasted_booking_value')); ?>
		</div>
		<div class="form-group">
			<?= $this->formElement($form->get('submit')); ?>
		</div>
		</div>
		<div class="col-md-6">
		<div class="form-group">
			<?= $this->formLabel($form->get('quanitity')); ?>
			<?= $this->formElement($form->get('quanitity')); ?>
			<?= $this->formElementErrors($form->get('quanitity')); ?>
		</div>
		<div class="form-group">
			<?= $this->formLabel($form->get('expected_close_date')); ?>
			<?= $this->formElement($form->get('expected_close_date')); ?>
			<?= $this->formElementErrors($form->get('expected_close_date')); ?>
		</div>
		<div class="form-group">
			<?= $this->formLabel($form->get('expected_month')); ?>
			<?= $this->formElement($form->get('expected_month')); ?>
			<?= $this->formElementErrors($form->get('expected_month')); ?>
		</div>
		<div class="form-group">
			<?= $this->formLabel($form->get('close_probability')); ?>
			<?= $this->formElement($form->get('close_probability')); ?>
			<?= $this->formElementErrors($form->get('close_probability')); ?>
		</div>
		<div class="form-group">
			<?= $this->formLabel($form->get('next_action')); ?>
			<?= $this->formElement($form->get('next_action')); ?>
			<?= $this->formElementErrors($form->get('next_action')); ?>
		</div>
		<div class="form-group">
			<?= $this->formLabel($form->get('last_contacted_date')); ?>
			<?= $this->formElement($form->get('last_contacted_date')); ?>
			<?= $this->formElementErrors($form->get('last_contacted_date')); ?>
		</div>
		<div class="form-group">
			<?= $this->formLabel($form->get('remarks')); ?>
			<?= $this->formElement($form->get('remarks')); ?>
			<?= $this->formElementErrors($form->get('remarks')); ?>
		</div>
		<div class="form-group">
			<?= $this->formLabel($form->get('contacted_type')); ?>
			<?= $this->formElement($form->get('contacted_type')); ?>
			<?= $this->formElementErrors($form->get('contacted_type')); ?>
		</div>
		<div class="form-group">
			<?= $this->formLabel($form->get('contact_id')); ?>
			<?= $this->formElement($form->get('contact_id')); ?>
			<?= $this->formElementErrors($form->get('contact_id')); ?>
		</div>

			</div>

   
		</div>
		<?= $this->form()->closeTag(); ?>
	</div>
	</div>
</div>