<?php
$title = $this->translate('Add Products');
$this->pageBreadcrumbs()->setTitle($title);
$this->headTitle($title);
$this->pageBreadcrumbs()->setItems([
            $this->translate('Products')=>$this->url('products'),
            $this->translate('Add')=>$this->url('products', ['action'=>'add']),
            ]);
$this->mainMenu()->setActiveItemId('masters');
$form->get('name')->setAttributes(['class'=>'form-control','placeholder'=>'Name']);
$form->get('status')->setAttributes(['id' => 'status']);
$form->get('submit')->setAttributes(['class'=>'btn btn-primary'])->setValue($this->translate('Add Products'));
$form->prepare();
$this->PageActions()->setItems([
            ['label'=>'Back to Products','url'=>$this->url('products'),'icon'=>'fa fa-arrow-left','class'=>'btn-primary'],
            ]);
?>
<div class="row">
  <div class="col-md-6">
    <div class="card">
			<div class="card-header">
				<h4 class="card-title">Add Products</h4>
			</div>
			<div class="card-body">
        <?= $this->form()->openTag($form); ?>
        <div class="form-group">
            <?= $this->formLabel($form->get('name')); ?>
            <?= $this->formElement($form->get('name')); ?>
            <?= $this->formElementErrors($form->get('name')); ?>
        </div>
		<div class="form-group">
			
			  <?= $this->formElement($form->get('status')); ?>
			  <?= $this->formLabel($form->get('status')); ?>
			<?= $this->formElementErrors($form->get('status')); ?>
		</div>
        <?= $this->formElement($form->get('submit')); ?>
        <?= $this->form()->closeTag(); ?>
    </div>
	</div>
	</div>
</div>