<head>
        <meta charset="utf-8">
        <?= $this->headTitle('Airkom Group')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/favicons/favicon.ico'])
            ->prependStylesheet($this->basePath('vendor/jqvmap/css/jqvmap.min.css'))
            ->prependStylesheet($this->basePath('vendor/chartist/css/chartist.min.css'))
            ->prependStylesheet($this->basePath('vendor/jqvmap/css/jqvmap.min.css'))
            ->prependStylesheet($this->basePath('vendor/bootstrap-select/dist/css/bootstrap-select.min.css'))
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('vendor/owl-carousel/owl.carousel.css'))
            ->prependStylesheet($this->basePath('vendor/bootstrap-daterangepicker/daterangepicker.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript() ?>
    </head>