<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<?= $this->doctype() ?>
<html lang="en">
	<?= $this->render('layout/head') ?>
    <body>
	<!--*******************
        Preloader start
    ********************-->
    <div id="preloader">
        <div class="sk-three-bounce">
            <div class="sk-child sk-bounce1"></div>
            <div class="sk-child sk-bounce2"></div>
            <div class="sk-child sk-bounce3"></div>
        </div>
    </div>
    <!--*******************
        Preloader end
    ********************-->
	<div id="main-wrapper">
	<div class="nav-header">
            <a href="<?= $this->url('home') ?>" class="brand-logo">
                <img class="logo-abbr" src="<?= $this->basePath('images/logo') ?>" alt="">
                
                <img class="brand-title" src="<?= $this->basePath('images/logo-text.png') ?>" alt="">
            </a>
            <div class="nav-control">
                <div class="hamburger">
                    <span class="line"></span><span class="line"></span><span class="line"></span>
                </div>
            </div>
        </div>
	
	<?= $this->render('layout/header') ?>
	<?= $this->render('layout/sidebar') ?>
	
	<div class="content-body">
		<div class="container-fluid">
		<div class="page-titles">
			<h4><?= $this->pageBreadcrumbs()->getTitle(); ?>  </h4> 
			<?= $this->pageBreadcrumbs()->render(); ?> 
			<?= $this->PageActions()->render(); ?> 
		</div>
		
		<?= $this->flashMessenger()->render('error', ['alert', 'alert-danger']); ?>
		<?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
		<?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>
		
			<?= $this->content ?>
		</div>
	</div>
	
	<?= $this->render('layout/footer') ?>
        <?= $this->inlineScript()
            ->appendFile($this->basePath('vendor/global/global.min.js'))
            ->appendFile($this->basePath('vendor/bootstrap-select/dist/js/bootstrap-select.min.js')) 
            ->appendFile($this->basePath('vendor/chart.js/Chart.bundle.min.js')) 
            ->appendFile($this->basePath('vendor/owl-carousel/owl.carousel.js')) 
            ->appendFile($this->basePath('vendor/peity/jquery.peity.min.js')) 
			->appendFile($this->basePath('vendor/moment/moment.min.js')) 
			->appendFile($this->basePath('vendor/bootstrap-daterangepicker/daterangepicker.js')) 
            ->appendFile($this->basePath('js/plugins-init/bs-daterange-picker-init.js')) 
            ->appendFile($this->basePath('js/printThis.js')) 
          ?>
		  
		   <!-- Scripts -->
        <?= $this->headScript() ?>
		
				<script src="<?= $this->basePath('js/custom.min.js'); ?>" type="text/javascript"></script>
		<script src="<?= $this->basePath('js/deznav-init.js'); ?>" type="text/javascript"></script>
			
		
		<script>
		function carouselReview(){
			/*  testimonial one function by = owl.carousel.js */
			/*  testimonial one function by = owl.carousel.js */
			jQuery('.testimonial-one').owlCarousel({
				loop:true,
				margin:10,
				nav:false,
				center:true,
				dots: false,
				navText: ['<i class="fa fa-caret-left"></i>', '<i class="fa fa-caret-right"></i>'],
				responsive:{
					0:{
						items:2
					},
					400:{
						items:3
					},	
					700:{
						items:5
					},	
					991:{
						items:6
					},			
					1200:{
						items:4
					},
					1600:{
						items:5
					}
				}
			})	
		}
		jQuery(window).on('load',function(){
			setTimeout(function(){
				carouselReview();
			}, 1000); 
		});
	
	</script>
    </div>
	</body>
</html>