<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<?= $this->doctype() ?>
<html lang="en" class="h-100">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Airkom Group')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/favicons/favicon.ico'])
            ->prependStylesheet($this->basePath('css/style.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript() ?>
    </head>
    <body class="h-100">
        <div class="authincation h-100">
			<div class="container h-100">
				<?= $this->content ?>
			</div>
        </div>
        <?= $this->inlineScript()
            ->prependFile($this->basePath('vendor/global/global.min.js'))
            ->prependFile($this->basePath('vendor/bootstrap-select/dist/js/bootstrap-select.min.js')) 
            ->prependFile($this->basePath('js/custom.min.js')) 
            ->prependFile($this->basePath('js/deznav-init.js')) 
			
			?>
    </body>
</html>
