<?php 
	$path = (!empty($this->UserDetail()->getUserProfilePic())) ? $this->basePath().'/uploads/profile_pics/'.$this->UserDetail()->getUserProfilePic(): $this->basePath().'/images/user.jpg'; 
?>

<a class="nav-link" href="javascript:void(0)" role="button" data-toggle="dropdown">
	<div class="header-info">
		<span class="text-black">Hello, <strong><?= $this->UserDetail()->getFullName(); ?></strong></span>
		<p class="fs-12 mb-0"><?= $this->UserDetail()->getUserType(); ?></p>
	</div>
	<img src="<?=$path;?>" width="20" alt=""/>
</a>
<div class="dropdown-menu dropdown-menu-right">
	<a href="<?= $this->url('users', ['action'=>'view']) ?>" class="dropdown-item ai-icon">
		<svg id="icon-user1" xmlns="http://www.w3.org/2000/svg" class="text-primary" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"></path><circle cx="12" cy="7" r="4"></circle></svg>
		<span class="ml-2">Profile </span>
	</a>
	<a href="<?= $this->url('logout') ?>" class="dropdown-item ai-icon">
		<svg id="icon-logout" xmlns="http://www.w3.org/2000/svg" class="text-danger" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4"></path><polyline points="16 17 21 12 16 7"></polyline><line x1="21" y1="12" x2="9" y2="12"></line></svg>
		<span class="ml-2">Logout </span>
	</a>
</div>