<?php
$title = $this->translate('Add Probability');
$this->pageBreadcrumbs()->setTitle($title);
$this->headTitle($title);
$this->pageBreadcrumbs()->setItems([
            $this->translate('Probability')=>$this->url('probability'),
            $this->translate('Add')=>$this->url('probability', ['action'=>'add']),
            ]);
$this->mainMenu()->setActiveItemId('masters');
$form->get('name')->setAttributes(['class'=>'form-control','placeholder'=>'Probability Percentage']);
$form->get('status')->setAttributes(['id' => 'status']);
$form->get('submit')->setAttributes(['class'=>'btn btn-primary'])->setValue($this->translate('Add Probability'));
$form->prepare();
$this->PageActions()->setItems([
            ['label'=>'Back to Probabilities','url'=>$this->url('probability'),'icon'=>'arrow-left','class'=>'btn-primary'],
            ]);
?>
<div class="row">
  <div class="col-md-6">
    <div class="card">
			<div class="card-header">
				<h4 class="card-title">Add Probability</h4>
			</div>
			<div class="card-body">
        <?= $this->form()->openTag($form); ?>
        <div class="form-group">
            <?= $this->formLabel($form->get('name')); ?>
           <div class="input-group mb-2">
				<div class="input-group-prepend">
					<div class="input-group-text">%</div>
				</div>
				<?= $this->formElement($form->get('name')); ?>
			</div>
            <?= $this->formElementErrors($form->get('name')); ?>
        </div>
		<div class="form-group">
			
			  <?= $this->formElement($form->get('status')); ?>
			  <?= $this->formLabel($form->get('status')); ?>
			<?= $this->formElementErrors($form->get('status')); ?>
		</div>
        <?= $this->formElement($form->get('submit')); ?>
        <?= $this->form()->closeTag(); ?>
    </div>
	</div>
	</div>
</div>