<?php
$title = $this->translate('Roles');
$this->headTitle($title);
$this->pageBreadcrumbs()->setTitle($title);
$this->mainMenu()->setActiveItemId('settings');
$this->pageBreadcrumbs()->setItems([
            $this->translate('Home')=>$this->url('home'),
            $this->translate('Manage Roles')=>$this->url('roles'),
            ]);
$this->PageActions()->setItems([
            ['label'=>'Add Roles','url'=>$this->url('roles', ['action'=>'add']),'icon'=>'plus','class'=>'btn-primary'],
            ]);
?>

<div class="row">
	<div class="col-lg-12">
		<div class="card">
			<div class="card-header">
				<h4 class="card-title">Manage Roles</h4>
			</div>
			<div class="card-body">
				<div class="table-responsive">
					<table class="table table-responsive-md">
						<thead>
							<tr>
								<th><strong><?= $this->translate('ID') ?></strong></th>
								<th><strong><?= $this->translate('Name') ?></strong></th>
								<th><strong><?= $this->translate('Description') ?></strong></th>
								<th><strong><?= $this->translate('Date Created') ?></strong></th>
								<th class="fit-width"><strong><?= $this->translate('Actions') ?></strong></th>
							</tr>
						</thead>
						<tbody>
						 <?php foreach ($roles as $role): ?>
							<tr>
								<td><strong><?= $this->escapeHtml($role->getId()); ?></strong></td>
								<td><a class="tx-semibold" href="<?= $this->url('roles', ['action'=>'view', 'id'=>$role->getId()]); ?>">
                <?= $this->escapeHtml($role->getName()); ?>
            </a></td>
								<td><?= $this->escapeHtml($role->getDescription()); ?></td>
								<td><?= $this->escapeHtml($role->getDateCreated()); ?></td>
								<td>
								<a class="btn btn-light" href="<?= $this->url('roles',['action'=>'edit', 'id'=>$role->getId()]); ?>">
                 Edit
            </a>
			<a class="btn btn-danger" href="#" data-link="<?= $this->url('roles',
                    ['action'=>'delete', 'id'=>$role->getId()]); ?>" data-toggle="modal" data-target="#confirmDelete">
                Delete Role
            </a>
								</td>
							</tr>
							 <?php endforeach; ?>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>
<?= $this->partial('application/index/delete'); ?>