<?php
$title = $this->translate('View Role');
$this->headTitle($title);
$this->pageBreadcrumbs()->setTitle($title);
$this->mainMenu()->setActiveItemId('settings');
$this->pageBreadcrumbs()->setItems([
           $this->translate('Home')=>$this->url('home'),
           $this->translate('Manage Roles')=>$this->url('roles'),
           $this->translate('View Role')=>$this->url('roles', ['action'=>'view', 'id'=>$role->getId()])
            ]);
?>

<div class="col-xl-10">
                        <div class="card">
                            <div class="card-header">
                                <h4 class="card-title">Default Tab</h4>
                            </div>
                            <div class="card-body">
                                <!-- Nav tabs -->
                                <div class="default-tab">
                                    <ul class="nav nav-tabs" role="tablist">
                                        <li class="nav-item">
                                            <a class="nav-link active" data-toggle="tab" href="#roles"><i class="la la-user-tag mr-2"></i> Roles</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link" data-toggle="tab" href="#permissions"><i class="las la-key mr-2"></i> Permissions</a>
                                        </li>
                                    </ul>
                                    <div class="tab-content">
                                        <div class="tab-pane fade show active" id="roles" role="tabpanel">
                                            <div class="pt-4">
                                               <div class="table-responsive">
		<table class="table table-hover mg-t-30 mg-b-30 mg-md-t-0">
        <thead>
		<tr>
                <th><?= $this->translate('ID') ?>:</th>
                <th><?= $this->translate('Name') ?>:</th>
                <th><?= $this->translate('Description') ?>:</th>
                <th><?= $this->translate('Date Created') ?>:</th>
            </tr>
          </thead>
            <tr>
                <td><?= $this->escapeHtml($role->getId()) ?></td>
                <td><?= $this->escapeHtml($role->getName()) ?></td>
                <td><?= $this->escapeHtml($role->getDescription()) ?></td>
                <td><?= $this->escapeHtml($role->getDateCreated()) ?></td>
            </tr>
        </table>
		<a class="btn btn-primary mt-2" href="<?= $this->url('roles',['action'=>'edit', 'id'=>$role->getId()]); ?>">Edit Role</a>
      </div>
                                            </div>
                                        </div>
                                        <div class="tab-pane fade" id="permissions">
                                            <div class="pt-4">
                                                <div class="table-responsive">
		<table class="table table-hover  table-responsive-block">
		  <thead>      
		  <tr>
                <th><?= $this->translate('Name') ?></th>
                <th><?= $this->translate('Description') ?></th>
            </tr>
          </thead>
            <?php foreach($allPermissions as $permission): ?>
			
            <tr>
                <td>
                    <input type="checkbox" disabled <?php if (isset($effectivePermissions[$permission->getName()])) echo 'checked'; ?>>
                    <?= $this->escapeHtml($permission->getName()) ?>
                    <?php if (isset($effectivePermissions[$permission->getName()]) && $effectivePermissions[$permission->getName()]=='inherited'): ?>
                    <em>(inherited)</em>
                    <?php endif; ?>
                </td>
                <td><?= $this->escapeHtml($permission->getDescription()) ?></td>
            </tr>
            <?php endforeach; ?>
        </table>
      </div>
	  <a class="btn btn-primary mt-2" href="<?= $this->url('roles', ['action'=>'editPermissions', 'id'=>$role->getId()]) ?>">Edit Permissions</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>