<?php
$title = $this->translate('System UserType');
$this->headTitle($title);
$this->pageBreadcrumbs()->setTitle($title);
$this->mainMenu()->setActiveItemId('masters');
$this->pageBreadcrumbs()->setItems([
            $this->translate('System UserType')=>$this->url('system-usertype'),
            $this->translate('Listings')=>$this->url('system-usertype', ['action'=>'index']),
            ]);

$this->PageActions()->setItems([
            ['label'=>'Add System UserType','url'=>$this->url('system-usertype', ['action'=>'add']),'icon'=>'plus','class'=>'btn-primary'],
            ]);	
?>

<div class="row">
  <div class="col-12">
<div class="card">
			<div class="card-header">
				<h4 class="card-title">Manage UserTypes</h4>
			</div>
			<div class="card-body">

<div class="table-responsive">
<table class="table table-responsive-md">
<thead>
<tr>
	<th><strong><?= $this->translate('Id') ?></strong></th>
	<th><strong><?= $this->translate('Name') ?></strong></th>
	<th><strong><?= $this->translate('Confidential Data') ?></strong></th>
	<th><strong><?= $this->translate('Status') ?></strong></th>
	<th><strong><?= $this->translate('Date Created') ?></strong></th>
	<th class="fit-width" colspan="2"><strong><?= $this->translate('Actions') ?></strong></th>
</tr>
</thead>
<tbody>
<?php foreach ($system_usertype as $usertype) : ?>
<tr>
<td><?= $usertype->getID();?></td>
    <td><a href="<?= $this->url('system-usertype',['action'=>'edit','id' => $usertype->getId()]); ?>" class="tx-semibold"><?= $usertype->getName();?></a></td>
  <td><?= (($usertype->getConfidential() == '0')?'No':'Yes');?></td>
  <td><a href="<?= $this->url('system-usertype', ['action'=>'setstatus','id' => $usertype->getId()]); ?>"><?= ($usertype->getStatus()==1?'<i data-feather="toggle-right"></i>':'<i class="tx-gray-500" data-feather="toggle-left"></i>');?></a></td>
	<td><?= $usertype->getDateCreated();?></td>
	<td>
	<a href="<?= $this->url('system-usertype', array('controller' => 'system-usertype', 'action'=>'edit','id' => $usertype->getId())); ?>" class="btn btn-light"><i class="fa fa-pencil"></i></a>
    </td>
		<td>
		<a href="<?= $this->url('system-usertype',[ 'action'=>'delete','id' => $usertype->getId()]); ?>" class="btn btn-danger"><i class="fa fa-trash"></i></a>
    </td>
</tr>
<?php endforeach; ?>
</tbody>
</table></div>


	<?= $this->partial('application/partial/paginator', ['paginator'=>$this->paginator]); ?>

</div>
    </div>
    </div>
    </div>
