<?php
$title = $this->translate('Reports');
$this->headTitle($title);
$this->mainMenu()->setActiveItemId('settings');
$this->pageBreadcrumbs()->setTitle('User');
$this->pageBreadcrumbs()->setItems([
           $this->translate('Home')=>$this->url('home'),
           $this->translate('Manage Reports')=>$this->url('reports'),
            ]);
$this->PageActions()->setItems([
            ['label'=>'Add New User','url'=>$this->url('reports', ['action'=>'add']),'icon'=>'plus','class'=>'btn-primary'],
            ]);			
?>
<div class="row main-content">
<div class="card col-md-12">
<div class="card-header">
	<h4 class="card-title">All Reports</h4>
</div>
	<div class="card-body">
		<div class="col-md-12">
		<form id="user_filter_form" method="post" action="<?= $this->url('reports'); ?>">
			<div class="form-row">
				<div class="form-group col-sm-4">
				   <select class="form-control" id="s_user" name="s_user">
					<option value="">Select User</option>
						<?php foreach ($users as $user) { ?>
							<option <?= empty($search_array)?'':($search_array['s_user']==$user->getId()?'selected':''); ?> value="<?= $user->getId(); ?>"><?= $user->getFullName(); ?></option>
						<?php } ?>
					</select>
				</div>
				<div class="form-group col-sm-3">
				  <input class="form-control input-daterange-datepicker" id="s_daterange" name="s_daterange" />
				  </div>
				<div class="col-sm-3 mg-t-10 mg-sm-t-0">
				  <button type="submit" class="btn btn-primary btn-block mg-b-10">Generate Report</button>
				</div>
				<div class="col-sm-2 mg-t-10 mg-sm-t-0">
					  <a href="<?= $this->url('reports'); ?>" class="btn btn-light btn-block">Refresh</a>
				</div>
			</div>
		</form>
	</div>
	<div class="col-12">
		<?php print_r($report) ?>
		<?= $this->partial('application/partial/paginator', ['paginator'=>$this->paginator,'search'=>base64_encode(serialize($search_array))]); ?>
	</div>
</div>
</div>
</div>