<?php
$title = $this->translate('Reports');
$this->headTitle($title);
$this->mainMenu()->setActiveItemId('reports');
$this->pageBreadcrumbs()->setTitle('Summary of the Sales Team Performance');
$this->pageBreadcrumbs()->setItems([
           $this->translate('Home')=>$this->url('home'),
           $this->translate('Manage Reports')=>$this->url('reports'),
            ]);	
$this->PageActions()->setItems([
            ['label'=>'Print','url'=>'','icon'=>'print','class'=>'btn-primary printbtn'],
            ]);	
?>
<div class="row main-content">
<div class="card col-md-12">
<div class="card-header">
	<?php 
		function getDates($d){
			if(!empty($d)){
				$dates = explode(' - ', $d);
				$s = \Datetime::createFromFormat('d/m/Y', $dates[0])->format('d M');
				$e = \Datetime::createFromFormat('d/m/Y', $dates[1])->format('d M');
				return $s.' to '.$e; 
			}else{
				return;
			}
			
			return !empty($d)? 'from '.$d:'';
		}
	?>
	<h4 class="card-title"> <?= !empty($selectedUser)? $this->UserDetail()->getFullName($selectedUser):'' ?> <?= getDates($selectedDate) ?></h4>
</div>
	<div class="card-body">
		<div class="col-md-12">
		<form id="user_filter_form" method="post" action="<?= $this->url('reports'); ?>">
			<div class="form-row">
				<div class="form-group col-sm-4">
				   <select class="form-control" id="s_user" name="s_user">
					<option value="">Select User</option>
						<?php foreach ($users as $user) { ?>
							<option <?= empty($selectedUser)?'':($selectedUser==$user->getId()?'selected':''); ?> value="<?= $user->getId(); ?>"><?= $user->getFullName(); ?></option>
						<?php } ?>
					</select>
				</div>
				<div class="form-group col-sm-3">
				  <input class="form-control input-daterange-datepicker" id="s_daterange" name="s_daterange" value="<?=empty($selectedDate)?'':$selectedDate;?>"/>
				  </div>
				<div class="col-sm-3 mg-t-10 mg-sm-t-0">
				  <button type="submit" class="btn btn-primary btn-block mg-b-10">Generate Report</button>
				</div>
				<div class="col-sm-2 mg-t-10 mg-sm-t-0">
					  <a href="<?= $this->url('reports'); ?>" class="btn btn-light btn-block">Refresh</a>
				</div>
			</div>
		</form>
	</div>
	<div id="printTable" class="col-12">
		<div class="table-responsive">
			<table class="table table-responsive-md">
				<thead>
					<tr>
						<th><strong>Type of Sales Calls</strong></th>
						<th><strong>Target</strong></th>
						<th><strong>Performmed</strong></th>
						<th><strong>Efficiency</strong></th>
					</tr>
				</thead>
				<tbody>
				   <tr><td>No. of Cold Calls</td><td></td><td></td><td></td></tr>
					<tr><td>No. of OEM Calls</td><td></td><td></td><td></td></tr>
					<tr><td>No. of Prospect Calls</td><td></td><td></td><td></td></tr>
					<tr><td>No. of Order Calls</td><td></td><td></td><td></td></tr>
					<tr><td>No. Sales Payment Collection Calls</td><td></td><td></td><td></td></tr>
					<tr><td>No. of Form Collection Calls</td><td></td><td></td><td></td></tr>
					<tr><td>No. of Sales Issue Handling Calls</td><td></td><td></td><td></td></tr>
					<tr><td>No. of Service Calls</td><td></td><td></td><td></td></tr>
					<tr><td><strong>Up-to-date Call Efficiency</strong></td><td></td><td></td><td></td></tr>
				</tbody>
			</table>
			<br/>
			<table class="table table-responsive-md">
				<thead>
					<tr>
						<th><strong>Total no. of Calls</strong></th>
						<th><strong>Target</strong></th>
						<th><strong>Performed</strong></th>
						<th><strong>Efficiency</strong></th>
					</tr>
				</thead>
				<tbody>
					<tr><td>Total No. of Local Calls</td><td></td><td></td><td></td></tr>
					<tr><td>Total No. of Outstation Calls</td><td></td><td></td><td></td></tr>
					<tr><td><strong>Total Call Efficiency</strong></td><td></td><td></td><td></td></tr>
				</tbody>
			</table>
			<br/>
			<table class="table table-responsive-md">
				<thead>
					<tr>
						<th><strong>Description</strong></th>
						<th><strong>Value</strong></th>
						<th><strong>Unit</strong></th>
					</tr>
				</thead>
				<tbody>
					<tr><td>Monthly Total Distance Travelled by Bike</td><td></td><td>KMs</td></tr>
					<tr><td>Monthly Total Amount for the distance travelled by Bike</td><td></td><td>Rs.</td></tr>
					<tr><td>Monthly Total Amount spent for Conveyance (Local)</td><td></td><td>Rs.</td></tr>
					<tr><td><strong>Monthly Total Travel Expenses</strong></td><td></td><td>Rs.</td></tr>
				</tbody>
			</table>
			<br/>
			<table class="table table-responsive-md">
				<thead>
					<tr>
						<th><strong>Description</strong></th>
						<th><strong>Target</strong></th>
						<th><strong>Performed</strong></th>
						<th><strong>Efficiency</strong></th>
					</tr>
				</thead>
				<tbody>
					<tr><td>Up-to-date Sales Prospect Generated (<?= date('d-m-Y') ?>)</td><td></td><td></td><td></td></tr>
					<tr><td>Up-to-date Target Booking vs Order Booking</td><td></td><td></td><td></td></tr>
					<tr><td colspan="3"><strong>Overall Efficiency</strong></td><td></td></tr>
				</tbody>
			</table>
		</div>
	</div>
</div>
</div>
</div>

<style>
@media print {
    #printTable td {
        font-family:'arial';
    }
}
</style>