<?php
$title = $this->translate('Reports');
$this->headTitle($title);
$this->mainMenu()->setActiveItemId('reports');
$this->pageBreadcrumbs()->setTitle('Summary of the Sales Team Performance');
$this->pageBreadcrumbs()->setItems([
           $this->translate('Home')=>$this->url('home'),
           $this->translate('Manage Reports')=>$this->url('reports'),
            ]);	
$this->PageActions()->setItems([
            ['label'=>'Print','url'=>'','icon'=>'fa fa-print','class'=>'btn-primary printbtn'],
            ]);	
?>
<div class="row">
<div class="col-md-12">
<div class="card">
<div class="card-header">
	<?php 
		function getDates($d){
			if(!empty($d)){
				$dates = explode(' - ', $d);
				$s = \Datetime::createFromFormat('d/m/Y', $dates[0])->format('d M');
				$e = \Datetime::createFromFormat('d/m/Y', $dates[1])->format('d M');
				return $s.' to '.$e; 
			}else{
				return;
			}
			
			return !empty($d)? 'from '.$d:'';
		}
	?>
	<h4 class="card-title"> <?= !empty($selectedUser)? $this->UserDetail()->getFullName($selectedUser):'' ?> <?= getDates($selectedDate) ?></h4>
</div>
	<div class="card-body">
		<div class="col-md-12">
		<form id="user_filter_form" method="post" action="<?= $this->url('reports'); ?>">
			<div class="form-row">
				<div class="form-group col-sm-4">
				   <select class="form-control" id="s_user" name="s_user">
					<!--<option value="">Select User</option>-->
						<?php foreach ($users as $user) { ?>
							<option <?= empty($selectedUser)?'':($selectedUser==$user->getId()?'selected':''); ?> value="<?= $user->getId(); ?>"><?= $user->getFullName(); ?></option>
						<?php } ?>
					</select>
				</div>
				<div class="form-group col-sm-3">
				  <input class="form-control input-daterange-datepicker" id="s_daterange" name="s_daterange" value="<?=empty($selectedDate)?date('d/m/Y', strtotime('-30 day')).' - '.date('d/m/Y'):$selectedDate;?>"/>
				  </div>
				<div class="col-sm-3 mg-t-10 mg-sm-t-0">
				  <button type="submit" class="btn btn-primary btn-block mg-b-10">Generate Report</button>
				</div>
				<div class="col-sm-2 mg-t-10 mg-sm-t-0">
					  <a href="<?= $this->url('reports'); ?>" class="btn btn-light btn-block">Refresh</a>
				</div>
			</div>
		</form>
	</div>
	
<?php 

function checkValue($value){
	if(is_nan($value) || is_infinite($value)){
		return 0;
	}
	return round($value,2);
}

?>
	
<?php if(!empty($calls_array)){ ?>
	<div id="printTable" class="col-12">
		<div class="table-responsive">
			<table class="table table-responsive-md table-striped">
				<thead>
					<tr>
						<th><strong>TYPE OF SALES CALLS</strong></th>
						<th><strong>TARGET</strong></th>
						<th><strong>PERFORMED</strong></th>
						<th><strong>EFFICIENCY</strong></th>
					</tr>
				</thead>
				<tbody>
				<?php foreach ($calls_array as $key => $value){ 
					if($key == 'uptodate_call_efficiency') continue;
				?>
				   <tr><td>No. of <?= $key ?></td><td class="text-right"><?= $value['target'] ?></td><td class="text-right"><?= $value['performed'] ?></td><td class="text-right"><?= checkValue($value['efficiency']) ?> %</td></tr>
				<?php } ?>
					<tr><td><strong>Up-to-date Call Efficiency</strong></td><td class="text-right"><strong><?= $calls_array['uptodate_call_efficiency']['target']; ?></strong></td><td class="text-right"><strong><?= $calls_array['uptodate_call_efficiency']['performed']; ?></strong></td><td class="text-right"><strong><?= $calls_array['uptodate_call_efficiency']['efficiency']; ?> %</strong></td></tr>
				</tbody>
			</table>
			<br/>
			<table class="table table-responsive-md table-striped">
				<thead>
					<tr>
						<th><strong>TOTAL NO. OF CALLS</strong></th>
						<th><strong>TARGET</strong></th>
						<th><strong>PERFORMED</strong></th>
						<th><strong>EFFICIENCY</strong></th>
					</tr>
				</thead>
				<tbody>
				<?php foreach ($travels_array as $key => $value){ 
					if($key == 'total_call_efficiency') continue;
				?>
				   <tr><td>No. of <?= $key ?> Calls</td><td class="text-right"><?= $value['target'] ?></td><td class="text-right"><?= $value['performed'] ?></td><td class="text-right"><?= checkValue($value['efficiency']) ?> %</td></tr>
				<?php } ?>
					<tr><td><strong>Total Call Efficiency</strong></td><td class="text-right"><strong><?= $travels_array['total_call_efficiency']['target']; ?></strong></td><td class="text-right"><strong><?= $travels_array['total_call_efficiency']['performed']; ?></strong></td><td class="text-right"><strong><?= $travels_array['total_call_efficiency']['efficiency']; ?> %</strong></td></tr>
				</tbody>
			</table>
			<br/>
			<table class="table table-responsive-md table-striped">
				<thead>
					<tr>
						<th><strong>DESCRIPTION</strong></th>
						<th><strong>VALUE</strong></th>
						<th><strong>UNIT</strong></th>
					</tr>
				</thead>
				<tbody>
					<tr><td>Monthly Total Distance Travelled by Bike</td><td class="text-right"><?= $distance_array['travelled'] ?></td><td>KMs</td></tr>
					<tr><td>Monthly Total Amount for the distance travelled by Bike</td><td class="text-right"><?= number_format($distance_array['amountone'],2) ?></td><td>Rs.</td></tr>
					<tr><td>Monthly Total Amount spent for Conveyance (Local)</td><td class="text-right"><?= number_format($distance_array['amounttwo'],2) ?></td><td>Rs.</td></tr>
					<tr><td><strong>Monthly Total Travel Expenses</strong></td><td class="text-right"><strong><?= number_format($distance_array['total'],2) ?></strong></td><td><strong>Rs.</strong></td></tr>
				</tbody>
			</table>
			<br/>
			<table class="table table-responsive-md  table-striped">
				<thead>
					<tr>
						<th><strong>DESCRIPTION</strong></th>
						<th><strong>TARGET</strong></th>
						<th><strong>PERFORMED</strong></th>
						<th><strong>EFFICIENCY</strong></th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td>Up-to-date Sales Prospect Generated (<?= date('d-m-Y') ?>)</td>
						<td class="text-right"><?= number_format($sales_array['sales_prospect']['target'],0) ?></td>
						<td class="text-right"><?= number_format($sales_array['sales_prospect']['performed'],0) ?></td>
						<td class="text-right"><?= $sales_array['sales_prospect']['efficiency'] ?> %</td>
					</tr>
					<tr>
						<td>Up-to-date Target Booking vs Order Booking</td>
						<td class="text-right"><?= number_format($sales_array['target_booking']['target'],0) ?></td>
						<td class="text-right"><?= number_format($sales_array['target_booking']['performed'],0) ?></td>
						<td class="text-right"><?= $sales_array['target_booking']['efficiency'] ?> %</td>
					</tr>
					<tr>
						<td><strong>Overall Efficiency</strong></td><td class="text-right"><?= number_format($sales_array['total_sales_efficiency']['target'],0); ?></td>
						<td class="text-right"><?= number_format($sales_array['total_sales_efficiency']['performed'],0); ?></td>
						<td class="text-right"><strong><?= $sales_array['total_sales_efficiency']['efficiency']; ?> %</strong></td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
<?php } ?>
</div>
</div>
</div>
</div>
